[package]
name = "actinv-gui"
publish = false
version = "0.1.0-preview.1"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "ACTINV native scientific desktop"

[features]
default = ["desktop"]
desktop = []

[[bin]]
name = "actinv-gui"
path = "src/main.rs"
required-features = ["desktop"]

[lib]
name = "actinv_web"
crate-type = ["cdylib", "rlib"]

[dependencies]
actinv-data = { path = "../actinv-data", version = "=1.2.1" }
actinv-core = { path = "../actinv-core", version = "=1.2.1" }
eframe = { version = "=0.36.1", default-features = false, features = ["default_fonts", "glow", "x11", "wayland", "persistence"] }
egui_extras = { version = "=0.36.1", features = ["syntect"] }
egui_plot = "=0.37.0"
image = { version = "0.25", default-features = false, features = ["png"] }
rfd = "0.16"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["float_roundtrip"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
actinv-cli = { path = "../actinv-cli", version = "=1.2.1" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
rfd = { version = "0.16", features = ["file-handle-inner"] }
console_error_panic_hook = "0.1.7"
js-sys = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Blob", "Document", "Element", "HtmlCanvasElement", "HtmlElement", "Url", "Window"] }

[build-dependencies]
embed-resource = "=3.0.11"
