#!/usr/bin/env python3
"""Generate crates/actinv-core/src/cram_coeffs.rs from the CRAM coefficients recorded in ACT-P0 from
openmc.deplete.cram (Pusa 2016). Constants are generated, never transcribed: P5 found that hand-typing them
produced 32 wrong values that a transfer-function control catches immediately (r(0) must be exactly 1)."""
import json, os
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
SRC = os.path.join(ROOT, "data", "cram_coefficients.json")   # vendored: no control may read outside the clone
d = json.load(open(SRC)); out = ["//! CRAM coefficients — GENERATED by controls/gen_cram.py. DO NOT EDIT.",
    "//! " + d["citation"], f'//! Source: {os.path.basename(SRC)} (recorded in ACT-P0 from {d["source_module"].split("/")[-1]}, OpenMC {d["openmc_version"]}).', ""]
for name, key in (("CRAM16", "Cram16Solver"), ("CRAM48", "Cram48Solver")):
    c = d[key]
    out += [f"/// CRAM-{c['order']}, incomplete partial fractions.",
            f"pub const {name}_ALPHA0: f64 = {c['alpha0']!r};",
            f"pub const {name}_THETA: [(f64, f64); {len(c['theta_re'])}] = ["]
    out += [f"    ({r!r}, {i!r})," for r, i in zip(c["theta_re"], c["theta_im"])]
    out += ["];", f"pub const {name}_ALPHA: [(f64, f64); {len(c['alpha_re'])}] = ["]
    out += [f"    ({r!r}, {i!r})," for r, i in zip(c["alpha_re"], c["alpha_im"])]
    out += ["];", ""]
open(os.path.join(ROOT, "crates", "actinv-core", "src", "cram_coeffs.rs"), "w").write("\n".join(out))
print("cram_coeffs.rs generated:", d["citation"][:60])
